name: Release Suite

on:
  push:
    tags:
      - v0.*
      - v1.*

env:
  AUTOINSTALL: true
  VERBOSE: true
  CI: true
  DEBIAN_FRONTEND: noninteractive
  CONTAINER_TOOL: docker
  RUSTFLAGS: "-D warnings"

jobs:
  build-x86_64-unknown-linux-gnu-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - run: bash scripts/set-build-description.sh
      - env:
          PASS_FEATURES: "default"
        run: make package-x86_64-unknown-linux-gnu-all
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-gnu.tar.gz
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-gnu.tar.gz"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-amd64.deb
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-amd64.deb"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-1.x86_64.rpm
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-1.x86_64.rpm"
